import assets5 from '../../assets/asset 5.jpeg'
import assets7 from '../../assets/asset 7.jpeg'

const CommonData = [
    {
        id: 1,
        img: assets5,
        heading: "Small Wedding Package",
        para: "Basic Package for 50 guests",
        price: "2,400.00",
        para2: "This package is perfect for the couple who wants a professional Wedding Planner by their side every step of the way to assist with budget management, vendor negotiations.",
        title: "Package Includes:",
        list1: "Exclu   sive Hire of the Venue from 9am until finish",
        list2: "Tea and Coffee Station after the Wedding Breakfast",
        list3: "Jugs of Iced Water on Tables",
        list4: "Jugs of Squash available at the bar (before 19.00)",
        list5: "Use of music system for background music",
        list6: "Lime Washed Chiavari Chairs - Plain",
    },
    {
        id: 2,
        img: assets7,
        heading: "Big Wedding Package",
        para: "Basic Package for 50 guests",
        price: "5,300.00",
        para2: "This package is perfect for the couple who wants a professional Wedding Planner by their side every step of the way to assist with budget management, vendor negotiations.",
        title: "Package Includes:",
        list1: "Exclusive Hire of the Venue from 9am until finish",
        list2: "Tea and Coffee Station after the Wedding Breakfast",
        list3: "Jugs of Iced Water on Tables",
        list4: "Jugs of Squash available at the bar (before 19.00)",
        list5: "Use of music system for background music",
        list6: "Lime Washed Chiavari Chairs - Plain",
    },
    // {
    //     id: 3,
    //     img: assets5,
    //     heading: "Small Wedding Package",
    //     para: "Basic Package for 50 guests",
    //     price: "2,400.00",
    //     para2: "This package is perfect for the couple who wants a professional Wedding Planner by their side every step of the way to assist with budget management, vendor negotiations.",
    //     title: "Package Includes:",
    //     list1: "Exclusive Hire of the Venue from 9am until finish",
    //     list2: "Tea and Coffee Station after the Wedding Breakfast",
    //     list3: "Jugs of Iced Water on Tables",
    //     list4: "Jugs of Squash available at the bar (before 19.00)",
    //     list5: "Use of music system for background music",
    //     list6: "Lime Washed Chiavari Chairs - Plain",
    // },
    // {
    //     id: 4,
    //     img: assets7,
    //     heading: "Small Wedding Package",
    //     para: "Basic Package for 50 guests",
    //     price: "2,400.00",
    //     para2: "This package is perfect for the couple who wants a professional Wedding Planner by their side every step of the way to assist with budget management, vendor negotiations.",
    //     title: "Package Includes:",
    //     list1: "Exclusive Hire of the Venue from 9am until finish",
    //     list2: "Tea and Coffee Station after the Wedding Breakfast",
    //     list3: "Jugs of Iced Water on Tables",
    //     list4: "Jugs of Squash available at the bar (before 19.00)",
    //     list5: "Use of music system for background music",
    //     list6: "Lime Washed Chiavari Chairs - Plain",
    // }
]

export default CommonData
